version: '3'
services:
  api:
    build: ./metalarchives-api
    container_name: "ma-api"
    depends_on:
      - mongodb
    networks:
      - default
    environment:
      - MONGO_URL=mongodb://mongodb:27017/metalarchives-api
      - DB_CATCH=${DB_CATCH}
  bot:
    build: ./metalarchives-telegram-bot
    container_name: "ma-bot"
    depends_on:
      - mongodb
      - redis
      - api
    networks:
      - default
    environment:
      - MONGO_URL=mongodb://mongodb:27017/metalarchives-bot
      - REDIS_URL=redis://redis:6379
      - API_URL=http://api:3000
      - BOT_TOKEN=<bot token goes here>
      - BOT_USERNAME=<bot username goes here>
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    volumes:
      - ./data:/data
    networks:
      - default
  redis:
    image: redis:latest
    container_name: "redis"
    networks:
      - default
networks:
  default:
    driver: bridge
